### ISSUE TITLE
(pq:query db "SELECT $1" 100) returns string ⇒ ("100") instead of integer

### ISSUE THREAD

**Issue by gnusupport** [anse1/emacs-libpq#19] opened 2021-06-21 21:02 UTC
I am expecting that 

(pq:query db "SELECT $1" 100) ⇒ ("100")

returns integer instead of a string. I suspect bug here.

Only way it would work is:

(pq:query db "SELECT $1::integer" 100) ⇒ (100)

which makes everything cumbersome. It forces me to use function `format` which is then unsafe for users' input. I would rather like to switch to using `pq:query` parameters, but this problem is here.

**Comment by anse1** [comment] 2021-06-24 07:23
GNU Support writes:

> (pq:query db "SELECT $1" 100) ⇒ ("100")
> (pq:query db "SELECT $1::integer" 100) ⇒ (100)

Not a bug per se.  The module isn't specifying any parameter types when
invoking libpq and lets the server infer the types.  It can't do this
when your query doesn't contain anything to narrow down the type such as
columns, function calls or casts and adding a cast is the solution.

I'm a bit afraid that letting the module specify a type may lead to
errors in situations where there is no implicit cast available to the
wanted type whereas auto-detecting it as the wanted type would have
worked.

Guess it's worth a closer look.

--8<---------------cut here---------------start------------->8---
     'paramTypes[]'
          Specifies, by OID, the data types to be assigned to the
          parameter symbols.  If 'paramTypes' is 'NULL', or any
          particular element in the array is zero, the server infers a
          data type for the parameter symbol in the same way it would do
          for an untyped literal string.
--8<---------------cut here---------------end--------------->8---

**Comment by gnusupport** [comment] 2021-06-24 07:44
* Andreas Seltenreich ***@***.***> [2021-06-24 10:23]:
> GNU Support writes:
> 
> > (pq:query db "SELECT $1" 100) ⇒ ("100")
> > (pq:query db "SELECT $1::integer" 100) ⇒ (100)
> 
> Not a bug per se.  The module isn't specifying any parameter types when
> invoking libpq and lets the server infer the types.  It can't do this
> when your query doesn't contain anything to narrow down the type such as
> columns, function calls or casts and adding a cast is the solution.
> 
> I'm a bit afraid that letting the module specify a type may lead to
> errors in situations where there is no implicit cast available to the
> wanted type whereas auto-detecting it as the wanted type would have
> worked.

That I understand, so I need to cast. Then close it.

**Closed as completed** 2022-02-25 10:33 UTC
